### PR TITLE
Update translations.php

### PR DESCRIPTION
**Pull request by frankboettcher**
Added german translation

### CODE REVIEW

**Comment by DzikuVx** [comment]
@Frankie1977 Outstanding. But could you please make sensor ID 8 not 7, so BH1750FVI and my DIY work together? And please make it disabled by default. 
Ah, also LIGHT_SENSOR_ADDR is used for BH1750FVI. Please make it have its own address constant so they really con work together

**Comment by frankboettcher** [comment]
Will do so!

**Comment by DzikuVx** [comment]
Cool

**Comment by DzikuVx** [comment]
Thank you!

**Pull request merged**
